import '../models/doctor_model.dart';

final List<DoctorModel> mockDoctors = [
  DoctorModel(
    id: 'doc_1',
    name: 'Dr. Karmix Devid',
    email: 'doctor@healthcare.com',
    phone: '+1 234 567 8901',
    specialty: 'Neurologist',
    bio:
        'Dr. Karmix Devid is a specialist who diagnoses and treats disorders of the brain, spinal cord, and nervous system.',
    education: 'MD - Neurology, Harvard Medical School',
    experienceYears: 6,
    rating: 4.9,
    reviewCount: 2800,
    patientCount: 1200,
    consultationFee: 300,
    isAvailable: true,
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    availableSlots: [
      '08:00 AM', '08:30 AM', '09:00 AM', '09:30 AM',
      '10:00 AM', '10:30 AM', '12:00 PM', '12:30 PM',
      '01:00 PM', '01:30 PM', '05:00 PM', '05:30 PM',
      '07:00 PM', '07:30 PM',
    ],
    hospitalName: 'City General Hospital',
    address: '123 Medical Center Dr, New York, NY',
  ),
  DoctorModel(
    id: 'doc_2',
    name: 'Dr. Sarah Johnson',
    email: 'sarah.johnson@healthcare.com',
    phone: '+1 234 567 8902',
    specialty: 'Cardiologist',
    bio:
        'Dr. Sarah Johnson is a board-certified cardiologist with expertise in interventional cardiology and heart failure management.',
    education: 'MD - Cardiology, Johns Hopkins University',
    experienceYears: 12,
    rating: 4.8,
    reviewCount: 3500,
    patientCount: 2100,
    consultationFee: 350,
    isAvailable: true,
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    availableSlots: [
      '09:00 AM', '09:30 AM', '10:00 AM', '10:30 AM',
      '11:00 AM', '02:00 PM', '02:30 PM', '03:00 PM',
    ],
    hospitalName: 'Heart Care Center',
    address: '456 Cardiac Ave, New York, NY',
  ),
  DoctorModel(
    id: 'doc_3',
    name: 'Dr. Michael Chen',
    email: 'michael.chen@healthcare.com',
    phone: '+1 234 567 8903',
    specialty: 'Dermatologist',
    bio:
        'Dr. Michael Chen specializes in medical and cosmetic dermatology, treating conditions from acne to skin cancer.',
    education: 'MD - Dermatology, Stanford University',
    experienceYears: 8,
    rating: 4.7,
    reviewCount: 1900,
    patientCount: 1500,
    consultationFee: 250,
    isAvailable: true,
    availableDays: ['Mon', 'Wed', 'Fri'],
    availableSlots: [
      '08:00 AM', '08:30 AM', '09:00 AM', '09:30 AM',
      '10:00 AM', '10:30 AM', '11:00 AM',
    ],
    hospitalName: 'Skin Care Clinic',
    address: '789 Derma St, New York, NY',
  ),
  DoctorModel(
    id: 'doc_4',
    name: 'Dr. Emily Roberts',
    email: 'emily.roberts@healthcare.com',
    phone: '+1 234 567 8904',
    specialty: 'Pediatrician',
    bio:
        'Dr. Emily Roberts is a compassionate pediatrician dedicated to providing comprehensive healthcare for children from infancy through adolescence.',
    education: 'MD - Pediatrics, Yale University',
    experienceYears: 10,
    rating: 4.9,
    reviewCount: 4200,
    patientCount: 3000,
    consultationFee: 200,
    isAvailable: true,
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    availableSlots: [
      '08:00 AM', '08:30 AM', '09:00 AM', '09:30 AM',
      '10:00 AM', '10:30 AM', '11:00 AM', '11:30 AM',
      '02:00 PM', '02:30 PM', '03:00 PM', '03:30 PM',
    ],
    hospitalName: 'Children\'s Medical Center',
    address: '321 Kids Ave, New York, NY',
  ),
  DoctorModel(
    id: 'doc_5',
    name: 'Dr. James Wilson',
    email: 'james.wilson@healthcare.com',
    phone: '+1 234 567 8905',
    specialty: 'Orthopedic',
    bio:
        'Dr. James Wilson is an orthopedic surgeon specializing in sports injuries, joint replacement, and spine surgery.',
    education: 'MD - Orthopedic Surgery, Columbia University',
    experienceYears: 15,
    rating: 4.6,
    reviewCount: 2300,
    patientCount: 1800,
    consultationFee: 400,
    isAvailable: true,
    availableDays: ['Tue', 'Wed', 'Thu', 'Fri'],
    availableSlots: [
      '09:00 AM', '09:30 AM', '10:00 AM', '10:30 AM',
      '11:00 AM', '03:00 PM', '03:30 PM', '04:00 PM',
    ],
    hospitalName: 'Bone & Joint Center',
    address: '654 Ortho Lane, New York, NY',
  ),
  DoctorModel(
    id: 'doc_6',
    name: 'Dr. Lisa Anderson',
    email: 'lisa.anderson@healthcare.com',
    phone: '+1 234 567 8906',
    specialty: 'Gynecologist',
    bio:
        'Dr. Lisa Anderson provides comprehensive women\'s healthcare including prenatal care, gynecological surgery, and fertility treatments.',
    education: 'MD - OB/GYN, University of Pennsylvania',
    experienceYears: 11,
    rating: 4.8,
    reviewCount: 3100,
    patientCount: 2500,
    consultationFee: 280,
    isAvailable: true,
    availableDays: ['Mon', 'Tue', 'Thu', 'Fri'],
    availableSlots: [
      '08:00 AM', '08:30 AM', '09:00 AM', '09:30 AM',
      '10:00 AM', '02:00 PM', '02:30 PM', '03:00 PM',
      '04:00 PM', '04:30 PM',
    ],
    hospitalName: 'Women\'s Health Center',
    address: '987 Women St, New York, NY',
  ),
  DoctorModel(
    id: 'doc_7',
    name: 'Dr. Robert Martinez',
    email: 'robert.martinez@healthcare.com',
    phone: '+1 234 567 8907',
    specialty: 'Psychiatrist',
    bio:
        'Dr. Robert Martinez is a psychiatrist specializing in mood disorders, anxiety, PTSD, and addiction psychiatry.',
    education: 'MD - Psychiatry, Duke University',
    experienceYears: 9,
    rating: 4.5,
    reviewCount: 1500,
    patientCount: 900,
    consultationFee: 320,
    isAvailable: true,
    availableDays: ['Mon', 'Wed', 'Fri'],
    availableSlots: [
      '10:00 AM', '10:30 AM', '11:00 AM', '11:30 AM',
      '02:00 PM', '02:30 PM', '03:00 PM', '03:30 PM',
    ],
    hospitalName: 'Mind Wellness Center',
    address: '147 Mental Health Dr, New York, NY',
  ),
  DoctorModel(
    id: 'doc_8',
    name: 'Dr. Amanda White',
    email: 'amanda.white@healthcare.com',
    phone: '+1 234 567 8908',
    specialty: 'Ophthalmologist',
    bio:
        'Dr. Amanda White is an eye specialist providing comprehensive eye care including LASIK surgery and cataract treatment.',
    education: 'MD - Ophthalmology, MIT',
    experienceYears: 7,
    rating: 4.7,
    reviewCount: 1800,
    patientCount: 1300,
    consultationFee: 275,
    isAvailable: true,
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu'],
    availableSlots: [
      '08:30 AM', '09:00 AM', '09:30 AM', '10:00 AM',
      '11:00 AM', '11:30 AM', '01:00 PM', '01:30 PM',
    ],
    hospitalName: 'Vision Care Institute',
    address: '258 Eye Lane, New York, NY',
  ),
  DoctorModel(
    id: 'doc_9',
    name: 'Dr. David Thompson',
    email: 'david.thompson@healthcare.com',
    phone: '+1 234 567 8909',
    specialty: 'ENT Specialist',
    bio:
        'Dr. David Thompson specializes in disorders of the ear, nose, and throat, including sinus surgery and hearing disorders.',
    education: 'MD - ENT, UCLA',
    experienceYears: 13,
    rating: 4.6,
    reviewCount: 2100,
    patientCount: 1600,
    consultationFee: 260,
    isAvailable: false,
    availableDays: ['Tue', 'Thu', 'Fri'],
    availableSlots: [
      '09:00 AM', '09:30 AM', '10:00 AM', '10:30 AM',
      '02:00 PM', '02:30 PM',
    ],
    hospitalName: 'ENT Medical Center',
    address: '369 ENT Blvd, New York, NY',
  ),
  DoctorModel(
    id: 'doc_10',
    name: 'Dr. Jennifer Lee',
    email: 'jennifer.lee@healthcare.com',
    phone: '+1 234 567 8910',
    specialty: 'General Physician',
    bio:
        'Dr. Jennifer Lee is a general physician providing primary healthcare, preventive medicine, and chronic disease management.',
    education: 'MD - Internal Medicine, NYU',
    experienceYears: 5,
    rating: 4.4,
    reviewCount: 1100,
    patientCount: 800,
    consultationFee: 150,
    isAvailable: true,
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    availableSlots: [
      '08:00 AM', '08:30 AM', '09:00 AM', '09:30 AM',
      '10:00 AM', '10:30 AM', '11:00 AM', '11:30 AM',
      '12:00 PM', '12:30 PM', '02:00 PM', '02:30 PM',
      '03:00 PM', '03:30 PM', '04:00 PM', '04:30 PM',
      '05:00 PM', '05:30 PM',
    ],
    hospitalName: 'City General Hospital',
    address: '123 Medical Center Dr, New York, NY',
  ),
];
