import '../models/appointment_model.dart';

final List<AppointmentModel> mockAppointments = [
  // Patient 1 (Alexa Basu) appointments
  AppointmentModel(
    id: 'apt_1',
    doctorId: 'doc_1',
    doctorName: 'Dr. Karmix Devid',
    doctorSpecialty: 'Neurologist',
    patientId: 'pat_1',
    patientName: 'Alexa Basu',
    date: DateTime(2026, 3, 12),
    timeSlot: '10:00 AM - 11:00 AM',
    status: 'Confirmed',
    type: 'In Person',
    fee: 300,
    notes: 'Follow-up for migraine treatment',
  ),
  AppointmentModel(
    id: 'apt_2',
    doctorId: 'doc_2',
    doctorName: 'Dr. Sarah Johnson',
    doctorSpecialty: 'Cardiologist',
    patientId: 'pat_1',
    patientName: 'Alexa Basu',
    date: DateTime(2026, 3, 18),
    timeSlot: '09:00 AM - 09:30 AM',
    status: 'Pending',
    type: 'Online',
    fee: 350,
    notes: 'Annual heart checkup',
  ),
  AppointmentModel(
    id: 'apt_3',
    doctorId: 'doc_4',
    doctorName: 'Dr. Emily Roberts',
    doctorSpecialty: 'Pediatrician',
    patientId: 'pat_1',
    patientName: 'Alexa Basu',
    date: DateTime(2026, 2, 10),
    timeSlot: '08:00 AM - 08:30 AM',
    status: 'Completed',
    type: 'In Person',
    fee: 200,
    notes: 'Child vaccination',
    prescriptionId: 'presc_1',
  ),
  AppointmentModel(
    id: 'apt_4',
    doctorId: 'doc_3',
    doctorName: 'Dr. Michael Chen',
    doctorSpecialty: 'Dermatologist',
    patientId: 'pat_1',
    patientName: 'Alexa Basu',
    date: DateTime(2026, 1, 25),
    timeSlot: '09:00 AM - 09:30 AM',
    status: 'Cancelled',
    type: 'In Person',
    fee: 250,
  ),
  // Patient 2 appointments
  AppointmentModel(
    id: 'apt_5',
    doctorId: 'doc_1',
    doctorName: 'Dr. Karmix Devid',
    doctorSpecialty: 'Neurologist',
    patientId: 'pat_2',
    patientName: 'Marcus Williams',
    date: DateTime(2026, 3, 5),
    timeSlot: '08:00 AM - 08:30 AM',
    status: 'Confirmed',
    type: 'In Person',
    fee: 300,
    notes: 'First visit - recurring headaches',
  ),
  AppointmentModel(
    id: 'apt_6',
    doctorId: 'doc_5',
    doctorName: 'Dr. James Wilson',
    doctorSpecialty: 'Orthopedic',
    patientId: 'pat_2',
    patientName: 'Marcus Williams',
    date: DateTime(2026, 2, 20),
    timeSlot: '09:00 AM - 09:30 AM',
    status: 'Completed',
    type: 'In Person',
    fee: 400,
    prescriptionId: 'presc_3',
  ),
  // Patient 3 appointments
  AppointmentModel(
    id: 'apt_7',
    doctorId: 'doc_6',
    doctorName: 'Dr. Lisa Anderson',
    doctorSpecialty: 'Gynecologist',
    patientId: 'pat_3',
    patientName: 'Sophia Martinez',
    date: DateTime(2026, 3, 15),
    timeSlot: '02:00 PM - 02:30 PM',
    status: 'Confirmed',
    type: 'Online',
    fee: 280,
    notes: 'Regular checkup',
  ),
  AppointmentModel(
    id: 'apt_8',
    doctorId: 'doc_10',
    doctorName: 'Dr. Jennifer Lee',
    doctorSpecialty: 'General Physician',
    patientId: 'pat_3',
    patientName: 'Sophia Martinez',
    date: DateTime(2026, 2, 5),
    timeSlot: '10:00 AM - 10:30 AM',
    status: 'Completed',
    type: 'In Person',
    fee: 150,
    prescriptionId: 'presc_4',
  ),
  // Patient 4 appointments
  AppointmentModel(
    id: 'apt_9',
    doctorId: 'doc_2',
    doctorName: 'Dr. Sarah Johnson',
    doctorSpecialty: 'Cardiologist',
    patientId: 'pat_4',
    patientName: 'Daniel Kim',
    date: DateTime(2026, 3, 8),
    timeSlot: '10:00 AM - 10:30 AM',
    status: 'Confirmed',
    type: 'In Person',
    fee: 350,
    notes: 'ECG review',
  ),
  AppointmentModel(
    id: 'apt_10',
    doctorId: 'doc_7',
    doctorName: 'Dr. Robert Martinez',
    doctorSpecialty: 'Psychiatrist',
    patientId: 'pat_4',
    patientName: 'Daniel Kim',
    date: DateTime(2026, 3, 20),
    timeSlot: '10:00 AM - 10:30 AM',
    status: 'Pending',
    type: 'Online',
    fee: 320,
  ),
  // Patient 5 appointments
  AppointmentModel(
    id: 'apt_11',
    doctorId: 'doc_8',
    doctorName: 'Dr. Amanda White',
    doctorSpecialty: 'Ophthalmologist',
    patientId: 'pat_5',
    patientName: 'Olivia Brown',
    date: DateTime(2026, 3, 10),
    timeSlot: '09:00 AM - 09:30 AM',
    status: 'Confirmed',
    type: 'In Person',
    fee: 275,
    notes: 'Vision test annual',
  ),
  AppointmentModel(
    id: 'apt_12',
    doctorId: 'doc_9',
    doctorName: 'Dr. David Thompson',
    doctorSpecialty: 'ENT Specialist',
    patientId: 'pat_5',
    patientName: 'Olivia Brown',
    date: DateTime(2026, 2, 15),
    timeSlot: '02:00 PM - 02:30 PM',
    status: 'Completed',
    type: 'In Person',
    fee: 260,
    prescriptionId: 'presc_5',
  ),
  // Patient 6 appointments
  AppointmentModel(
    id: 'apt_13',
    doctorId: 'doc_1',
    doctorName: 'Dr. Karmix Devid',
    doctorSpecialty: 'Neurologist',
    patientId: 'pat_6',
    patientName: 'Ethan Davis',
    date: DateTime(2026, 3, 22),
    timeSlot: '12:00 PM - 12:30 PM',
    status: 'Pending',
    type: 'In Person',
    fee: 300,
  ),
  AppointmentModel(
    id: 'apt_14',
    doctorId: 'doc_3',
    doctorName: 'Dr. Michael Chen',
    doctorSpecialty: 'Dermatologist',
    patientId: 'pat_6',
    patientName: 'Ethan Davis',
    date: DateTime(2026, 2, 8),
    timeSlot: '08:00 AM - 08:30 AM',
    status: 'Completed',
    type: 'Online',
    fee: 250,
    prescriptionId: 'presc_6',
  ),
  // Patient 7 appointments
  AppointmentModel(
    id: 'apt_15',
    doctorId: 'doc_4',
    doctorName: 'Dr. Emily Roberts',
    doctorSpecialty: 'Pediatrician',
    patientId: 'pat_7',
    patientName: 'Isabella Garcia',
    date: DateTime(2026, 3, 28),
    timeSlot: '08:00 AM - 08:30 AM',
    status: 'Pending',
    type: 'In Person',
    fee: 200,
  ),
  // Patient 8 appointments
  AppointmentModel(
    id: 'apt_16',
    doctorId: 'doc_5',
    doctorName: 'Dr. James Wilson',
    doctorSpecialty: 'Orthopedic',
    patientId: 'pat_8',
    patientName: 'William Taylor',
    date: DateTime(2026, 3, 3),
    timeSlot: '03:00 PM - 03:30 PM',
    status: 'Confirmed',
    type: 'In Person',
    fee: 400,
    notes: 'Knee replacement follow-up',
  ),
  AppointmentModel(
    id: 'apt_17',
    doctorId: 'doc_5',
    doctorName: 'Dr. James Wilson',
    doctorSpecialty: 'Orthopedic',
    patientId: 'pat_8',
    patientName: 'William Taylor',
    date: DateTime(2026, 1, 15),
    timeSlot: '10:00 AM - 10:30 AM',
    status: 'Completed',
    type: 'In Person',
    fee: 400,
    prescriptionId: 'presc_7',
  ),
  // Patient 9 appointments
  AppointmentModel(
    id: 'apt_18',
    doctorId: 'doc_6',
    doctorName: 'Dr. Lisa Anderson',
    doctorSpecialty: 'Gynecologist',
    patientId: 'pat_9',
    patientName: 'Mia Anderson',
    date: DateTime(2026, 3, 14),
    timeSlot: '08:00 AM - 08:30 AM',
    status: 'Confirmed',
    type: 'In Person',
    fee: 280,
  ),
  // Patient 10 appointments
  AppointmentModel(
    id: 'apt_19',
    doctorId: 'doc_10',
    doctorName: 'Dr. Jennifer Lee',
    doctorSpecialty: 'General Physician',
    patientId: 'pat_10',
    patientName: 'Alexander Thomas',
    date: DateTime(2026, 3, 6),
    timeSlot: '08:00 AM - 08:30 AM',
    status: 'Confirmed',
    type: 'Online',
    fee: 150,
  ),
  AppointmentModel(
    id: 'apt_20',
    doctorId: 'doc_2',
    doctorName: 'Dr. Sarah Johnson',
    doctorSpecialty: 'Cardiologist',
    patientId: 'pat_10',
    patientName: 'Alexander Thomas',
    date: DateTime(2026, 2, 25),
    timeSlot: '09:30 AM - 10:00 AM',
    status: 'Completed',
    type: 'In Person',
    fee: 350,
    prescriptionId: 'presc_8',
  ),
  // Additional appointments for various patients
  AppointmentModel(
    id: 'apt_21',
    doctorId: 'doc_7',
    doctorName: 'Dr. Robert Martinez',
    doctorSpecialty: 'Psychiatrist',
    patientId: 'pat_11',
    patientName: 'Charlotte Moore',
    date: DateTime(2026, 3, 25),
    timeSlot: '02:00 PM - 02:30 PM',
    status: 'Pending',
    type: 'Online',
    fee: 320,
  ),
  AppointmentModel(
    id: 'apt_22',
    doctorId: 'doc_8',
    doctorName: 'Dr. Amanda White',
    doctorSpecialty: 'Ophthalmologist',
    patientId: 'pat_12',
    patientName: 'Benjamin Harris',
    date: DateTime(2026, 3, 11),
    timeSlot: '11:00 AM - 11:30 AM',
    status: 'Confirmed',
    type: 'In Person',
    fee: 275,
  ),
  AppointmentModel(
    id: 'apt_23',
    doctorId: 'doc_3',
    doctorName: 'Dr. Michael Chen',
    doctorSpecialty: 'Dermatologist',
    patientId: 'pat_13',
    patientName: 'Ava Jackson',
    date: DateTime(2026, 3, 16),
    timeSlot: '09:00 AM - 09:30 AM',
    status: 'Confirmed',
    type: 'In Person',
    fee: 250,
  ),
  AppointmentModel(
    id: 'apt_24',
    doctorId: 'doc_1',
    doctorName: 'Dr. Karmix Devid',
    doctorSpecialty: 'Neurologist',
    patientId: 'pat_14',
    patientName: 'Henry Clark',
    date: DateTime(2026, 2, 28),
    timeSlot: '01:00 PM - 01:30 PM',
    status: 'Confirmed',
    type: 'In Person',
    fee: 300,
  ),
  AppointmentModel(
    id: 'apt_25',
    doctorId: 'doc_4',
    doctorName: 'Dr. Emily Roberts',
    doctorSpecialty: 'Pediatrician',
    patientId: 'pat_15',
    patientName: 'Luna Rivera',
    date: DateTime(2026, 3, 30),
    timeSlot: '10:00 AM - 10:30 AM',
    status: 'Pending',
    type: 'In Person',
    fee: 200,
  ),
  AppointmentModel(
    id: 'apt_26',
    doctorId: 'doc_9',
    doctorName: 'Dr. David Thompson',
    doctorSpecialty: 'ENT Specialist',
    patientId: 'pat_2',
    patientName: 'Marcus Williams',
    date: DateTime(2026, 1, 20),
    timeSlot: '09:30 AM - 10:00 AM',
    status: 'Completed',
    type: 'In Person',
    fee: 260,
    prescriptionId: 'presc_9',
  ),
  AppointmentModel(
    id: 'apt_27',
    doctorId: 'doc_10',
    doctorName: 'Dr. Jennifer Lee',
    doctorSpecialty: 'General Physician',
    patientId: 'pat_4',
    patientName: 'Daniel Kim',
    date: DateTime(2026, 1, 10),
    timeSlot: '11:00 AM - 11:30 AM',
    status: 'Cancelled',
    type: 'Online',
    fee: 150,
  ),
  AppointmentModel(
    id: 'apt_28',
    doctorId: 'doc_6',
    doctorName: 'Dr. Lisa Anderson',
    doctorSpecialty: 'Gynecologist',
    patientId: 'pat_5',
    patientName: 'Olivia Brown',
    date: DateTime(2026, 2, 1),
    timeSlot: '04:00 PM - 04:30 PM',
    status: 'Completed',
    type: 'In Person',
    fee: 280,
    prescriptionId: 'presc_10',
  ),
  AppointmentModel(
    id: 'apt_29',
    doctorId: 'doc_2',
    doctorName: 'Dr. Sarah Johnson',
    doctorSpecialty: 'Cardiologist',
    patientId: 'pat_8',
    patientName: 'William Taylor',
    date: DateTime(2026, 3, 1),
    timeSlot: '02:00 PM - 02:30 PM',
    status: 'Rescheduled',
    type: 'In Person',
    fee: 350,
  ),
  AppointmentModel(
    id: 'apt_30',
    doctorId: 'doc_1',
    doctorName: 'Dr. Karmix Devid',
    doctorSpecialty: 'Neurologist',
    patientId: 'pat_9',
    patientName: 'Mia Anderson',
    date: DateTime(2026, 2, 27),
    timeSlot: '05:00 PM - 05:30 PM',
    status: 'Confirmed',
    type: 'Online',
    fee: 300,
    notes: 'Consultation for chronic headache',
  ),
];
