import '../models/billing_model.dart';

final List<BillingModel> mockBillings = [
  BillingModel(id: 'bill_1', patientId: 'pat_1', patientName: 'Alexa Basu', doctorId: 'doc_1', doctorName: 'Dr. Karmix Devid', appointmentId: 'apt_1', date: DateTime(2026, 3, 12), amount: 300, status: 'Pending', paymentMethod: 'Card', description: 'Consultation - Neurologist'),
  BillingModel(id: 'bill_2', patientId: 'pat_1', patientName: 'Alexa Basu', doctorId: 'doc_2', doctorName: 'Dr. Sarah Johnson', appointmentId: 'apt_2', date: DateTime(2026, 3, 18), amount: 350, status: 'Pending', paymentMethod: 'Card', description: 'Online Consultation - Cardiologist'),
  BillingModel(id: 'bill_3', patientId: 'pat_1', patientName: 'Alexa Basu', doctorId: 'doc_4', doctorName: 'Dr. Emily Roberts', appointmentId: 'apt_3', date: DateTime(2026, 2, 10), amount: 200, status: 'Paid', paymentMethod: 'Card', description: 'Consultation - Pediatrician'),
  BillingModel(id: 'bill_4', patientId: 'pat_2', patientName: 'Marcus Williams', doctorId: 'doc_1', doctorName: 'Dr. Karmix Devid', appointmentId: 'apt_5', date: DateTime(2026, 3, 5), amount: 300, status: 'Paid', paymentMethod: 'Cash', description: 'Consultation - Neurologist'),
  BillingModel(id: 'bill_5', patientId: 'pat_2', patientName: 'Marcus Williams', doctorId: 'doc_5', doctorName: 'Dr. James Wilson', appointmentId: 'apt_6', date: DateTime(2026, 2, 20), amount: 400, status: 'Paid', paymentMethod: 'Card', description: 'Consultation - Orthopedic'),
  BillingModel(id: 'bill_6', patientId: 'pat_3', patientName: 'Sophia Martinez', doctorId: 'doc_6', doctorName: 'Dr. Lisa Anderson', appointmentId: 'apt_7', date: DateTime(2026, 3, 15), amount: 280, status: 'Pending', paymentMethod: 'Card', description: 'Online Consultation - Gynecologist'),
  BillingModel(id: 'bill_7', patientId: 'pat_3', patientName: 'Sophia Martinez', doctorId: 'doc_10', doctorName: 'Dr. Jennifer Lee', appointmentId: 'apt_8', date: DateTime(2026, 2, 5), amount: 150, status: 'Paid', paymentMethod: 'UPI', description: 'Consultation - General Physician'),
  BillingModel(id: 'bill_8', patientId: 'pat_4', patientName: 'Daniel Kim', doctorId: 'doc_2', doctorName: 'Dr. Sarah Johnson', appointmentId: 'apt_9', date: DateTime(2026, 3, 8), amount: 350, status: 'Pending', paymentMethod: 'Card', description: 'Consultation - Cardiologist'),
  BillingModel(id: 'bill_9', patientId: 'pat_5', patientName: 'Olivia Brown', doctorId: 'doc_8', doctorName: 'Dr. Amanda White', appointmentId: 'apt_11', date: DateTime(2026, 3, 10), amount: 275, status: 'Overdue', paymentMethod: 'Card', description: 'Consultation - Ophthalmologist'),
  BillingModel(id: 'bill_10', patientId: 'pat_5', patientName: 'Olivia Brown', doctorId: 'doc_9', doctorName: 'Dr. David Thompson', appointmentId: 'apt_12', date: DateTime(2026, 2, 15), amount: 260, status: 'Paid', paymentMethod: 'Cash', description: 'Consultation - ENT Specialist'),
  BillingModel(id: 'bill_11', patientId: 'pat_6', patientName: 'Ethan Davis', doctorId: 'doc_3', doctorName: 'Dr. Michael Chen', appointmentId: 'apt_14', date: DateTime(2026, 2, 8), amount: 250, status: 'Paid', paymentMethod: 'Card', description: 'Online Consultation - Dermatologist'),
  BillingModel(id: 'bill_12', patientId: 'pat_8', patientName: 'William Taylor', doctorId: 'doc_5', doctorName: 'Dr. James Wilson', appointmentId: 'apt_16', date: DateTime(2026, 3, 3), amount: 400, status: 'Overdue', paymentMethod: 'Card', description: 'Consultation - Orthopedic'),
  BillingModel(id: 'bill_13', patientId: 'pat_8', patientName: 'William Taylor', doctorId: 'doc_5', doctorName: 'Dr. James Wilson', appointmentId: 'apt_17', date: DateTime(2026, 1, 15), amount: 400, status: 'Paid', paymentMethod: 'Card', description: 'Consultation - Orthopedic'),
  BillingModel(id: 'bill_14', patientId: 'pat_9', patientName: 'Mia Anderson', doctorId: 'doc_6', doctorName: 'Dr. Lisa Anderson', appointmentId: 'apt_18', date: DateTime(2026, 3, 14), amount: 280, status: 'Pending', paymentMethod: 'UPI', description: 'Consultation - Gynecologist'),
  BillingModel(id: 'bill_15', patientId: 'pat_10', patientName: 'Alexander Thomas', doctorId: 'doc_10', doctorName: 'Dr. Jennifer Lee', appointmentId: 'apt_19', date: DateTime(2026, 3, 6), amount: 150, status: 'Paid', paymentMethod: 'Card', description: 'Online Consultation - General Physician'),
  BillingModel(id: 'bill_16', patientId: 'pat_10', patientName: 'Alexander Thomas', doctorId: 'doc_2', doctorName: 'Dr. Sarah Johnson', appointmentId: 'apt_20', date: DateTime(2026, 2, 25), amount: 350, status: 'Paid', paymentMethod: 'Card', description: 'Consultation - Cardiologist'),
  BillingModel(id: 'bill_17', patientId: 'pat_11', patientName: 'Charlotte Moore', doctorId: 'doc_7', doctorName: 'Dr. Robert Martinez', appointmentId: 'apt_21', date: DateTime(2026, 3, 25), amount: 320, status: 'Pending', paymentMethod: 'Card', description: 'Online Consultation - Psychiatrist'),
  BillingModel(id: 'bill_18', patientId: 'pat_12', patientName: 'Benjamin Harris', doctorId: 'doc_8', doctorName: 'Dr. Amanda White', appointmentId: 'apt_22', date: DateTime(2026, 3, 11), amount: 275, status: 'Overdue', paymentMethod: 'Cash', description: 'Consultation - Ophthalmologist'),
  BillingModel(id: 'bill_19', patientId: 'pat_14', patientName: 'Henry Clark', doctorId: 'doc_1', doctorName: 'Dr. Karmix Devid', appointmentId: 'apt_24', date: DateTime(2026, 2, 28), amount: 300, status: 'Paid', paymentMethod: 'Card', description: 'Consultation - Neurologist'),
  BillingModel(id: 'bill_20', patientId: 'pat_15', patientName: 'Luna Rivera', doctorId: 'doc_4', doctorName: 'Dr. Emily Roberts', appointmentId: 'apt_25', date: DateTime(2026, 3, 30), amount: 200, status: 'Pending', paymentMethod: 'Card', description: 'Consultation - Pediatrician'),
];
