import '../models/prescription_model.dart';

final List<PrescriptionModel> mockPrescriptions = [
  PrescriptionModel(
    id: 'presc_1',
    appointmentId: 'apt_3',
    doctorId: 'doc_4',
    doctorName: 'Dr. Emily Roberts',
    patientId: 'pat_1',
    patientName: 'Alexa Basu',
    date: DateTime(2026, 2, 10),
    diagnosis: 'Seasonal Flu with mild fever',
    medicines: [
      MedicineItem(name: 'Paracetamol', dosage: '500mg', frequency: 'Twice daily', duration: '5 days', instructions: 'After meals'),
      MedicineItem(name: 'Cetirizine', dosage: '10mg', frequency: 'Once daily', duration: '7 days', instructions: 'At bedtime'),
      MedicineItem(name: 'Vitamin C', dosage: '1000mg', frequency: 'Once daily', duration: '14 days', instructions: 'Morning'),
    ],
    notes: 'Rest and drink plenty of fluids. Revisit if fever persists for more than 3 days.',
    followUpDate: DateTime(2026, 2, 24),
  ),
  PrescriptionModel(
    id: 'presc_2',
    appointmentId: 'apt_1',
    doctorId: 'doc_1',
    doctorName: 'Dr. Karmix Devid',
    patientId: 'pat_1',
    patientName: 'Alexa Basu',
    date: DateTime(2026, 1, 15),
    diagnosis: 'Tension-type Headache',
    medicines: [
      MedicineItem(name: 'Sumatriptan', dosage: '50mg', frequency: 'As needed', duration: '30 days', instructions: 'At onset of migraine'),
      MedicineItem(name: 'Amitriptyline', dosage: '25mg', frequency: 'Once daily', duration: '30 days', instructions: 'At bedtime'),
    ],
    notes: 'Track headache frequency and triggers. Follow up in 1 month.',
    followUpDate: DateTime(2026, 3, 12),
  ),
  PrescriptionModel(
    id: 'presc_3',
    appointmentId: 'apt_6',
    doctorId: 'doc_5',
    doctorName: 'Dr. James Wilson',
    patientId: 'pat_2',
    patientName: 'Marcus Williams',
    date: DateTime(2026, 2, 20),
    diagnosis: 'Lumbar Strain',
    medicines: [
      MedicineItem(name: 'Ibuprofen', dosage: '400mg', frequency: 'Three times daily', duration: '7 days', instructions: 'After meals'),
      MedicineItem(name: 'Methocarbamol', dosage: '500mg', frequency: 'Twice daily', duration: '5 days', instructions: 'With water'),
      MedicineItem(name: 'Diclofenac Gel', dosage: '1%', frequency: 'Three times daily', duration: '10 days', instructions: 'Apply on affected area'),
    ],
    notes: 'Avoid heavy lifting. Apply ice for 15 min every 2 hours. Start physiotherapy.',
    followUpDate: DateTime(2026, 3, 5),
  ),
  PrescriptionModel(
    id: 'presc_4',
    appointmentId: 'apt_8',
    doctorId: 'doc_10',
    doctorName: 'Dr. Jennifer Lee',
    patientId: 'pat_3',
    patientName: 'Sophia Martinez',
    date: DateTime(2026, 2, 5),
    diagnosis: 'Upper Respiratory Tract Infection',
    medicines: [
      MedicineItem(name: 'Amoxicillin', dosage: '500mg', frequency: 'Three times daily', duration: '7 days', instructions: 'After meals'),
      MedicineItem(name: 'Bromhexine', dosage: '8mg', frequency: 'Three times daily', duration: '5 days', instructions: 'Before meals'),
      MedicineItem(name: 'Loratadine', dosage: '10mg', frequency: 'Once daily', duration: '5 days', instructions: 'Morning'),
    ],
    notes: 'Complete the full course of antibiotics. Gargle with warm salt water.',
  ),
  PrescriptionModel(
    id: 'presc_5',
    appointmentId: 'apt_12',
    doctorId: 'doc_9',
    doctorName: 'Dr. David Thompson',
    patientId: 'pat_5',
    patientName: 'Olivia Brown',
    date: DateTime(2026, 2, 15),
    diagnosis: 'Sinusitis',
    medicines: [
      MedicineItem(name: 'Augmentin', dosage: '625mg', frequency: 'Twice daily', duration: '7 days', instructions: 'After meals'),
      MedicineItem(name: 'Fluticasone Nasal Spray', dosage: '50mcg', frequency: 'Twice daily', duration: '14 days', instructions: 'Each nostril'),
      MedicineItem(name: 'Montelukast', dosage: '10mg', frequency: 'Once daily', duration: '14 days', instructions: 'At bedtime'),
    ],
    notes: 'Use steam inhalation twice daily. Avoid cold air exposure.',
    followUpDate: DateTime(2026, 3, 1),
  ),
  PrescriptionModel(
    id: 'presc_6',
    appointmentId: 'apt_14',
    doctorId: 'doc_3',
    doctorName: 'Dr. Michael Chen',
    patientId: 'pat_6',
    patientName: 'Ethan Davis',
    date: DateTime(2026, 2, 8),
    diagnosis: 'Contact Dermatitis',
    medicines: [
      MedicineItem(name: 'Hydrocortisone Cream', dosage: '1%', frequency: 'Twice daily', duration: '10 days', instructions: 'Thin layer on affected area'),
      MedicineItem(name: 'Fexofenadine', dosage: '180mg', frequency: 'Once daily', duration: '14 days', instructions: 'With water'),
      MedicineItem(name: 'Moisturizing Lotion', dosage: 'Apply liberally', frequency: 'Three times daily', duration: '30 days', instructions: 'After bathing'),
    ],
    notes: 'Avoid known irritants. Use fragrance-free products.',
  ),
  PrescriptionModel(
    id: 'presc_7',
    appointmentId: 'apt_17',
    doctorId: 'doc_5',
    doctorName: 'Dr. James Wilson',
    patientId: 'pat_8',
    patientName: 'William Taylor',
    date: DateTime(2026, 1, 15),
    diagnosis: 'Osteoarthritis - Right Knee',
    medicines: [
      MedicineItem(name: 'Celecoxib', dosage: '200mg', frequency: 'Once daily', duration: '30 days', instructions: 'With food'),
      MedicineItem(name: 'Glucosamine', dosage: '1500mg', frequency: 'Once daily', duration: '90 days', instructions: 'Morning'),
      MedicineItem(name: 'Calcium + Vitamin D3', dosage: '500mg + 250IU', frequency: 'Twice daily', duration: '90 days', instructions: 'After meals'),
    ],
    notes: 'Physiotherapy 3 times a week. Knee exercises as instructed. Consider knee replacement if symptoms worsen.',
    followUpDate: DateTime(2026, 3, 3),
  ),
  PrescriptionModel(
    id: 'presc_8',
    appointmentId: 'apt_20',
    doctorId: 'doc_2',
    doctorName: 'Dr. Sarah Johnson',
    patientId: 'pat_10',
    patientName: 'Alexander Thomas',
    date: DateTime(2026, 2, 25),
    diagnosis: 'Mild Hypertension',
    medicines: [
      MedicineItem(name: 'Amlodipine', dosage: '5mg', frequency: 'Once daily', duration: '30 days', instructions: 'Morning'),
      MedicineItem(name: 'Aspirin', dosage: '75mg', frequency: 'Once daily', duration: '30 days', instructions: 'After lunch'),
      MedicineItem(name: 'Atorvastatin', dosage: '10mg', frequency: 'Once daily', duration: '30 days', instructions: 'At bedtime'),
    ],
    notes: 'Regular BP monitoring. Low sodium diet. Exercise 30 min/day. Follow up in 1 month.',
    followUpDate: DateTime(2026, 3, 25),
  ),
  PrescriptionModel(
    id: 'presc_9',
    appointmentId: 'apt_26',
    doctorId: 'doc_9',
    doctorName: 'Dr. David Thompson',
    patientId: 'pat_2',
    patientName: 'Marcus Williams',
    date: DateTime(2026, 1, 20),
    diagnosis: 'Acute Otitis Media',
    medicines: [
      MedicineItem(name: 'Ciprofloxacin Ear Drops', dosage: '0.3%', frequency: 'Three times daily', duration: '7 days', instructions: '3 drops each ear'),
      MedicineItem(name: 'Ibuprofen', dosage: '400mg', frequency: 'As needed', duration: '5 days', instructions: 'For pain'),
    ],
    notes: 'Keep ears dry. Avoid swimming. Follow up if symptoms persist.',
  ),
  PrescriptionModel(
    id: 'presc_10',
    appointmentId: 'apt_28',
    doctorId: 'doc_6',
    doctorName: 'Dr. Lisa Anderson',
    patientId: 'pat_5',
    patientName: 'Olivia Brown',
    date: DateTime(2026, 2, 1),
    diagnosis: 'Iron Deficiency Anemia',
    medicines: [
      MedicineItem(name: 'Ferrous Sulfate', dosage: '325mg', frequency: 'Twice daily', duration: '60 days', instructions: 'On empty stomach'),
      MedicineItem(name: 'Folic Acid', dosage: '5mg', frequency: 'Once daily', duration: '60 days', instructions: 'Morning'),
      MedicineItem(name: 'Vitamin B12', dosage: '1000mcg', frequency: 'Once daily', duration: '30 days', instructions: 'After breakfast'),
    ],
    notes: 'Include iron-rich foods: spinach, red meat, lentils. Repeat CBC after 2 months.',
    followUpDate: DateTime(2026, 4, 1),
  ),
  PrescriptionModel(
    id: 'presc_11',
    appointmentId: 'apt_1',
    doctorId: 'doc_1',
    doctorName: 'Dr. Karmix Devid',
    patientId: 'pat_1',
    patientName: 'Alexa Basu',
    date: DateTime(2025, 12, 10),
    diagnosis: 'Migraine with Aura',
    medicines: [
      MedicineItem(name: 'Propranolol', dosage: '40mg', frequency: 'Twice daily', duration: '30 days', instructions: 'Morning and evening'),
      MedicineItem(name: 'Rizatriptan', dosage: '10mg', frequency: 'As needed', duration: '30 days', instructions: 'At onset of migraine, max 2/day'),
    ],
    notes: 'Avoid triggers: bright lights, stress, lack of sleep. Maintain migraine diary.',
    followUpDate: DateTime(2026, 1, 15),
  ),
  PrescriptionModel(
    id: 'presc_12',
    appointmentId: 'apt_9',
    doctorId: 'doc_2',
    doctorName: 'Dr. Sarah Johnson',
    patientId: 'pat_4',
    patientName: 'Daniel Kim',
    date: DateTime(2026, 1, 8),
    diagnosis: 'Atrial Fibrillation',
    medicines: [
      MedicineItem(name: 'Metoprolol', dosage: '50mg', frequency: 'Twice daily', duration: '30 days', instructions: 'With food'),
      MedicineItem(name: 'Warfarin', dosage: '5mg', frequency: 'Once daily', duration: '30 days', instructions: 'Evening, same time daily'),
      MedicineItem(name: 'Digoxin', dosage: '0.25mg', frequency: 'Once daily', duration: '30 days', instructions: 'Morning'),
    ],
    notes: 'Regular INR monitoring. Avoid vitamin K-rich foods. Report any bleeding immediately.',
    followUpDate: DateTime(2026, 2, 8),
  ),
  PrescriptionModel(
    id: 'presc_13',
    appointmentId: 'apt_7',
    doctorId: 'doc_6',
    doctorName: 'Dr. Lisa Anderson',
    patientId: 'pat_3',
    patientName: 'Sophia Martinez',
    date: DateTime(2026, 1, 15),
    diagnosis: 'PCOS - Polycystic Ovary Syndrome',
    medicines: [
      MedicineItem(name: 'Metformin', dosage: '500mg', frequency: 'Twice daily', duration: '90 days', instructions: 'After meals'),
      MedicineItem(name: 'Myo-Inositol', dosage: '2g', frequency: 'Twice daily', duration: '90 days', instructions: 'Before meals'),
    ],
    notes: 'Regular exercise. Low glycemic diet. Weight management program. Follow up in 3 months with ultrasound.',
    followUpDate: DateTime(2026, 4, 15),
  ),
  PrescriptionModel(
    id: 'presc_14',
    appointmentId: 'apt_11',
    doctorId: 'doc_8',
    doctorName: 'Dr. Amanda White',
    patientId: 'pat_5',
    patientName: 'Olivia Brown',
    date: DateTime(2026, 1, 10),
    diagnosis: 'Myopia - Progressive',
    medicines: [
      MedicineItem(name: 'Atropine Eye Drops', dosage: '0.01%', frequency: 'Once daily', duration: '180 days', instructions: 'At bedtime, one drop each eye'),
      MedicineItem(name: 'Artificial Tears', dosage: '0.5%', frequency: 'Four times daily', duration: '30 days', instructions: 'As needed for dryness'),
    ],
    notes: 'New prescription glasses ordered. Follow the 20-20-20 rule for screen time. Next vision check in 6 months.',
    followUpDate: DateTime(2026, 7, 10),
  ),
  PrescriptionModel(
    id: 'presc_15',
    appointmentId: 'apt_15',
    doctorId: 'doc_4',
    doctorName: 'Dr. Emily Roberts',
    patientId: 'pat_7',
    patientName: 'Isabella Garcia',
    date: DateTime(2025, 12, 28),
    diagnosis: 'Allergic Rhinitis',
    medicines: [
      MedicineItem(name: 'Montelukast', dosage: '10mg', frequency: 'Once daily', duration: '30 days', instructions: 'At bedtime'),
      MedicineItem(name: 'Fluticasone Nasal Spray', dosage: '50mcg', frequency: 'Once daily', duration: '30 days', instructions: '2 sprays each nostril'),
      MedicineItem(name: 'Desloratadine', dosage: '5mg', frequency: 'Once daily', duration: '14 days', instructions: 'Morning'),
    ],
    notes: 'Avoid known allergens. Use air purifier at home. Saline nasal rinse daily.',
  ),
  PrescriptionModel(
    id: 'presc_16',
    appointmentId: 'apt_10',
    doctorId: 'doc_7',
    doctorName: 'Dr. Robert Martinez',
    patientId: 'pat_4',
    patientName: 'Daniel Kim',
    date: DateTime(2026, 1, 20),
    diagnosis: 'Generalized Anxiety Disorder',
    medicines: [
      MedicineItem(name: 'Sertraline', dosage: '50mg', frequency: 'Once daily', duration: '90 days', instructions: 'Morning with food'),
      MedicineItem(name: 'Clonazepam', dosage: '0.5mg', frequency: 'As needed', duration: '30 days', instructions: 'For acute anxiety, max once daily'),
    ],
    notes: 'Cognitive behavioral therapy recommended. Regular exercise. Mindfulness meditation practice.',
    followUpDate: DateTime(2026, 3, 20),
  ),
  PrescriptionModel(
    id: 'presc_17',
    appointmentId: 'apt_16',
    doctorId: 'doc_5',
    doctorName: 'Dr. James Wilson',
    patientId: 'pat_8',
    patientName: 'William Taylor',
    date: DateTime(2025, 12, 3),
    diagnosis: 'Rotator Cuff Tendinitis',
    medicines: [
      MedicineItem(name: 'Naproxen', dosage: '500mg', frequency: 'Twice daily', duration: '10 days', instructions: 'After meals'),
      MedicineItem(name: 'Capsaicin Cream', dosage: '0.1%', frequency: 'Three times daily', duration: '14 days', instructions: 'Apply on shoulder'),
    ],
    notes: 'Rotator cuff strengthening exercises. Ice application. Avoid overhead activities.',
    followUpDate: DateTime(2026, 1, 3),
  ),
  PrescriptionModel(
    id: 'presc_18',
    appointmentId: 'apt_19',
    doctorId: 'doc_10',
    doctorName: 'Dr. Jennifer Lee',
    patientId: 'pat_10',
    patientName: 'Alexander Thomas',
    date: DateTime(2026, 2, 6),
    diagnosis: 'Type 2 Diabetes - Early Stage',
    medicines: [
      MedicineItem(name: 'Metformin', dosage: '500mg', frequency: 'Twice daily', duration: '90 days', instructions: 'After meals'),
      MedicineItem(name: 'Glimepiride', dosage: '1mg', frequency: 'Once daily', duration: '90 days', instructions: 'Before breakfast'),
    ],
    notes: 'Regular blood sugar monitoring. Low carb diet. Walking 30 mins daily. HbA1c test in 3 months.',
    followUpDate: DateTime(2026, 5, 6),
  ),
  PrescriptionModel(
    id: 'presc_19',
    appointmentId: 'apt_21',
    doctorId: 'doc_7',
    doctorName: 'Dr. Robert Martinez',
    patientId: 'pat_11',
    patientName: 'Charlotte Moore',
    date: DateTime(2026, 2, 25),
    diagnosis: 'Major Depressive Disorder',
    medicines: [
      MedicineItem(name: 'Fluoxetine', dosage: '20mg', frequency: 'Once daily', duration: '90 days', instructions: 'Morning'),
      MedicineItem(name: 'Melatonin', dosage: '3mg', frequency: 'Once daily', duration: '30 days', instructions: 'At bedtime'),
    ],
    notes: 'Psychotherapy sessions weekly. Support group recommended. Emergency contact provided.',
    followUpDate: DateTime(2026, 3, 25),
  ),
  PrescriptionModel(
    id: 'presc_20',
    appointmentId: 'apt_23',
    doctorId: 'doc_3',
    doctorName: 'Dr. Michael Chen',
    patientId: 'pat_13',
    patientName: 'Ava Jackson',
    date: DateTime(2026, 2, 16),
    diagnosis: 'Acne Vulgaris',
    medicines: [
      MedicineItem(name: 'Adapalene Gel', dosage: '0.1%', frequency: 'Once daily', duration: '60 days', instructions: 'At bedtime, thin layer on face'),
      MedicineItem(name: 'Benzoyl Peroxide', dosage: '2.5%', frequency: 'Once daily', duration: '60 days', instructions: 'Morning, on affected areas'),
      MedicineItem(name: 'Doxycycline', dosage: '100mg', frequency: 'Once daily', duration: '30 days', instructions: 'After lunch, avoid sun exposure'),
    ],
    notes: 'Non-comedogenic skincare only. Sunscreen SPF 50 daily. Avoid picking at skin.',
    followUpDate: DateTime(2026, 4, 16),
  ),
];
