import '../models/notification_model.dart';

final List<NotificationModel> mockNotifications = [
  // Patient notifications
  NotificationModel(
    id: 'notif_1',
    title: 'Appointment Confirmed',
    message: 'Your appointment with Dr. Karmix Devid on Mar 12 at 10:00 AM has been confirmed.',
    type: 'appointment',
    role: 'patient',
    timestamp: DateTime(2026, 2, 27, 9, 30),
  ),
  NotificationModel(
    id: 'notif_2',
    title: 'Prescription Ready',
    message: 'Dr. Emily Roberts has uploaded your prescription. View it now.',
    type: 'prescription',
    role: 'patient',
    timestamp: DateTime(2026, 2, 26, 14, 0),
    isRead: true,
  ),
  NotificationModel(
    id: 'notif_3',
    title: 'Upcoming Appointment',
    message: 'Reminder: You have an appointment with Dr. Sarah Johnson tomorrow at 9:00 AM.',
    type: 'appointment',
    role: 'patient',
    timestamp: DateTime(2026, 2, 25, 18, 0),
  ),
  NotificationModel(
    id: 'notif_4',
    title: 'Lab Report Available',
    message: 'Your blood test results are now available. Tap to view.',
    type: 'general',
    role: 'patient',
    timestamp: DateTime(2026, 2, 24, 11, 30),
    isRead: true,
  ),
  NotificationModel(
    id: 'notif_5',
    title: 'Payment Successful',
    message: 'Payment of \$300 for appointment with Dr. Karmix Devid was successful.',
    type: 'payment',
    role: 'patient',
    timestamp: DateTime(2026, 2, 23, 16, 45),
    isRead: true,
  ),
  NotificationModel(
    id: 'notif_6',
    title: 'Follow-up Reminder',
    message: 'You have a follow-up appointment scheduled with Dr. Karmix Devid on Mar 12.',
    type: 'appointment',
    role: 'patient',
    timestamp: DateTime(2026, 2, 22, 10, 0),
  ),
  // Doctor notifications
  NotificationModel(
    id: 'notif_7',
    title: 'New Appointment',
    message: 'Alexa Basu has booked an appointment for Mar 12 at 10:00 AM.',
    type: 'appointment',
    role: 'doctor',
    timestamp: DateTime(2026, 2, 27, 8, 0),
  ),
  NotificationModel(
    id: 'notif_8',
    title: 'Appointment Cancelled',
    message: 'Marcus Williams has cancelled the appointment on Mar 5.',
    type: 'appointment',
    role: 'doctor',
    timestamp: DateTime(2026, 2, 26, 15, 30),
  ),
  NotificationModel(
    id: 'notif_9',
    title: 'Patient Review',
    message: 'Sophia Martinez has left a 5-star review for your consultation.',
    type: 'general',
    role: 'doctor',
    timestamp: DateTime(2026, 2, 25, 12, 0),
    isRead: true,
  ),
  NotificationModel(
    id: 'notif_10',
    title: 'Schedule Update',
    message: 'Your schedule for next week has been updated. 12 appointments confirmed.',
    type: 'general',
    role: 'doctor',
    timestamp: DateTime(2026, 2, 24, 9, 0),
    isRead: true,
  ),
  NotificationModel(
    id: 'notif_11',
    title: 'Payment Received',
    message: 'Payment of \$350 received from Daniel Kim for appointment on Mar 8.',
    type: 'payment',
    role: 'doctor',
    timestamp: DateTime(2026, 2, 23, 14, 15),
  ),
  NotificationModel(
    id: 'notif_12',
    title: 'Telemedicine Session',
    message: 'Upcoming online consultation with Mia Anderson at 5:00 PM today.',
    type: 'appointment',
    role: 'doctor',
    timestamp: DateTime(2026, 2, 27, 16, 0),
  ),
  // Admin notifications
  NotificationModel(
    id: 'notif_13',
    title: 'New Doctor Registration',
    message: 'Dr. Jennifer Lee has registered and is pending approval.',
    type: 'general',
    role: 'admin',
    timestamp: DateTime(2026, 2, 27, 7, 30),
  ),
  NotificationModel(
    id: 'notif_14',
    title: 'System Alert',
    message: 'Server response time increased. Average: 2.3s. Check system health.',
    type: 'general',
    role: 'admin',
    timestamp: DateTime(2026, 2, 26, 22, 0),
  ),
  NotificationModel(
    id: 'notif_15',
    title: 'Revenue Report',
    message: 'Weekly revenue report is ready. Total: \$15,420. View details.',
    type: 'payment',
    role: 'admin',
    timestamp: DateTime(2026, 2, 25, 8, 0),
    isRead: true,
  ),
  NotificationModel(
    id: 'notif_16',
    title: 'Patient Complaint',
    message: 'A new complaint has been filed by William Taylor. Action required.',
    type: 'general',
    role: 'admin',
    timestamp: DateTime(2026, 2, 24, 13, 30),
  ),
  NotificationModel(
    id: 'notif_17',
    title: 'Appointment Summary',
    message: 'Today: 24 appointments scheduled, 3 cancelled, 18 completed.',
    type: 'appointment',
    role: 'admin',
    timestamp: DateTime(2026, 2, 27, 18, 0),
    isRead: true,
  ),
  NotificationModel(
    id: 'notif_18',
    title: 'Overdue Payments',
    message: '5 invoices are overdue. Total: \$2,850. Send reminders.',
    type: 'payment',
    role: 'admin',
    timestamp: DateTime(2026, 2, 23, 9, 45),
  ),
];
