import '../models/doctor_model.dart';

final List<DoctorModel> mockDoctors = [
  DoctorModel(
    id: 'doc_1',
    name: 'Dr. Karmix Devid',
    email: 'doctor@healthcare.com',
    phone: '+1 234 567 8901',
    specialty: 'Neurologist',
    bio:
        'Dr. Karmix Devid is a specialist who diagnoses and treats disorders of the brain, spinal cord, and nervous system.',
    education: 'MD - Neurology, Harvard Medical School',
    experienceYears: 6,
    rating: 4.9,
    reviewCount: 2800,
    patientCount: 1200,
    consultationFee: 300,
    isAvailable: true,
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    availableSlots: [
      '08:00 AM', '08:30 AM', '09:00 AM', '09:30 AM',
      '10:00 AM', '10:30 AM', '12:00 PM', '12:30 PM',
      '01:00 PM', '01:30 PM', '05:00 PM', '05:30 PM',
      '07:00 PM', '07:30 PM',
    ],
    hospitalName: 'City General Hospital',
    address: '123 Medical Center Dr, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_1.jpg',
  ),
  DoctorModel(
    id: 'doc_2',
    name: 'Dr. Sarah Johnson',
    email: 'sarah.johnson@healthcare.com',
    phone: '+1 234 567 8902',
    specialty: 'Cardiologist',
    bio:
        'Dr. Sarah Johnson is a board-certified cardiologist with expertise in interventional cardiology and heart failure management.',
    education: 'MD - Cardiology, Johns Hopkins University',
    experienceYears: 12,
    rating: 4.8,
    reviewCount: 3500,
    patientCount: 2100,
    consultationFee: 350,
    isAvailable: true,
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    availableSlots: [
      '09:00 AM', '09:30 AM', '10:00 AM', '10:30 AM',
      '11:00 AM', '02:00 PM', '02:30 PM', '03:00 PM',
    ],
    hospitalName: 'Heart Care Center',
    address: '456 Cardiac Ave, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_2.jpg',
  ),
  DoctorModel(
    id: 'doc_3',
    name: 'Dr. Michael Chen',
    email: 'michael.chen@healthcare.com',
    phone: '+1 234 567 8903',
    specialty: 'Dermatologist',
    bio:
        'Dr. Michael Chen specializes in medical and cosmetic dermatology, treating conditions from acne to skin cancer.',
    education: 'MD - Dermatology, Stanford University',
    experienceYears: 8,
    rating: 4.7,
    reviewCount: 1900,
    patientCount: 1500,
    consultationFee: 250,
    isAvailable: true,
    availableDays: ['Mon', 'Wed', 'Fri'],
    availableSlots: [
      '08:00 AM', '08:30 AM', '09:00 AM', '09:30 AM',
      '10:00 AM', '10:30 AM', '11:00 AM',
    ],
    hospitalName: 'Skin Care Clinic',
    address: '789 Derma St, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_3.jpg',
  ),
  DoctorModel(
    id: 'doc_4',
    name: 'Dr. Emily Roberts',
    email: 'emily.roberts@healthcare.com',
    phone: '+1 234 567 8904',
    specialty: 'Pediatrician',
    bio:
        'Dr. Emily Roberts is a compassionate pediatrician dedicated to providing comprehensive healthcare for children from infancy through adolescence.',
    education: 'MD - Pediatrics, Yale University',
    experienceYears: 10,
    rating: 4.9,
    reviewCount: 4200,
    patientCount: 3000,
    consultationFee: 200,
    isAvailable: true,
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    availableSlots: [
      '08:00 AM', '08:30 AM', '09:00 AM', '09:30 AM',
      '10:00 AM', '10:30 AM', '11:00 AM', '11:30 AM',
      '02:00 PM', '02:30 PM', '03:00 PM', '03:30 PM',
    ],
    hospitalName: 'Children\'s Medical Center',
    address: '321 Kids Ave, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_4.jpg',
  ),
  DoctorModel(
    id: 'doc_5',
    name: 'Dr. James Wilson',
    email: 'james.wilson@healthcare.com',
    phone: '+1 234 567 8905',
    specialty: 'Orthopedic',
    bio:
        'Dr. James Wilson is an orthopedic surgeon specializing in sports injuries, joint replacement, and spine surgery.',
    education: 'MD - Orthopedic Surgery, Columbia University',
    experienceYears: 15,
    rating: 4.6,
    reviewCount: 2300,
    patientCount: 1800,
    consultationFee: 400,
    isAvailable: true,
    availableDays: ['Tue', 'Wed', 'Thu', 'Fri'],
    availableSlots: [
      '09:00 AM', '09:30 AM', '10:00 AM', '10:30 AM',
      '11:00 AM', '03:00 PM', '03:30 PM', '04:00 PM',
    ],
    hospitalName: 'Bone & Joint Center',
    address: '654 Ortho Lane, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_5.jpg',
  ),
  DoctorModel(
    id: 'doc_6',
    name: 'Dr. Lisa Anderson',
    email: 'lisa.anderson@healthcare.com',
    phone: '+1 234 567 8906',
    specialty: 'Gynecologist',
    bio:
        'Dr. Lisa Anderson provides comprehensive women\'s healthcare including prenatal care, gynecological surgery, and fertility treatments.',
    education: 'MD - OB/GYN, University of Pennsylvania',
    experienceYears: 11,
    rating: 4.8,
    reviewCount: 3100,
    patientCount: 2500,
    consultationFee: 280,
    isAvailable: true,
    availableDays: ['Mon', 'Tue', 'Thu', 'Fri'],
    availableSlots: [
      '08:00 AM', '08:30 AM', '09:00 AM', '09:30 AM',
      '10:00 AM', '02:00 PM', '02:30 PM', '03:00 PM',
      '04:00 PM', '04:30 PM',
    ],
    hospitalName: 'Women\'s Health Center',
    address: '987 Women St, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_6.jpg',
  ),
  DoctorModel(
    id: 'doc_7',
    name: 'Dr. Robert Martinez',
    email: 'robert.martinez@healthcare.com',
    phone: '+1 234 567 8907',
    specialty: 'Psychiatrist',
    bio:
        'Dr. Robert Martinez is a psychiatrist specializing in mood disorders, anxiety, PTSD, and addiction psychiatry.',
    education: 'MD - Psychiatry, Duke University',
    experienceYears: 9,
    rating: 4.5,
    reviewCount: 1500,
    patientCount: 900,
    consultationFee: 320,
    isAvailable: true,
    availableDays: ['Mon', 'Wed', 'Fri'],
    availableSlots: [
      '10:00 AM', '10:30 AM', '11:00 AM', '11:30 AM',
      '02:00 PM', '02:30 PM', '03:00 PM', '03:30 PM',
    ],
    hospitalName: 'Mind Wellness Center',
    address: '147 Mental Health Dr, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_7.jpg',
  ),
  DoctorModel(
    id: 'doc_8',
    name: 'Dr. Amanda White',
    email: 'amanda.white@healthcare.com',
    phone: '+1 234 567 8908',
    specialty: 'Ophthalmologist',
    bio:
        'Dr. Amanda White is an eye specialist providing comprehensive eye care including LASIK surgery and cataract treatment.',
    education: 'MD - Ophthalmology, MIT',
    experienceYears: 7,
    rating: 4.7,
    reviewCount: 1800,
    patientCount: 1300,
    consultationFee: 275,
    isAvailable: true,
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu'],
    availableSlots: [
      '08:30 AM', '09:00 AM', '09:30 AM', '10:00 AM',
      '11:00 AM', '11:30 AM', '01:00 PM', '01:30 PM',
    ],
    hospitalName: 'Vision Care Institute',
    address: '258 Eye Lane, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_8.jpg',
  ),
  DoctorModel(
    id: 'doc_9',
    name: 'Dr. David Thompson',
    email: 'david.thompson@healthcare.com',
    phone: '+1 234 567 8909',
    specialty: 'ENT Specialist',
    bio:
        'Dr. David Thompson specializes in disorders of the ear, nose, and throat, including sinus surgery and hearing disorders.',
    education: 'MD - ENT, UCLA',
    experienceYears: 13,
    rating: 4.6,
    reviewCount: 2100,
    patientCount: 1600,
    consultationFee: 260,
    isAvailable: false,
    availableDays: ['Tue', 'Thu', 'Fri'],
    availableSlots: [
      '09:00 AM', '09:30 AM', '10:00 AM', '10:30 AM',
      '02:00 PM', '02:30 PM',
    ],
    hospitalName: 'ENT Medical Center',
    address: '369 ENT Blvd, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_9.jpg',
  ),
  DoctorModel(
    id: 'doc_10',
    name: 'Dr. Jennifer Lee',
    email: 'jennifer.lee@healthcare.com',
    phone: '+1 234 567 8910',
    specialty: 'General Physician',
    bio:
        'Dr. Jennifer Lee is a general physician providing primary healthcare, preventive medicine, and chronic disease management.',
    education: 'MD - Internal Medicine, NYU',
    experienceYears: 5,
    rating: 4.4,
    reviewCount: 1100,
    patientCount: 800,
    consultationFee: 150,
    isAvailable: true,
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    availableSlots: [
      '08:00 AM', '08:30 AM', '09:00 AM', '09:30 AM',
      '10:00 AM', '10:30 AM', '11:00 AM', '11:30 AM',
      '12:00 PM', '12:30 PM', '02:00 PM', '02:30 PM',
      '03:00 PM', '03:30 PM', '04:00 PM', '04:30 PM',
      '05:00 PM', '05:30 PM',
    ],
    hospitalName: 'City General Hospital',
    address: '123 Medical Center Dr, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_10.jpg',
  ),

  // ── Additional Neurologists ──────────────────────────────────────────────
  DoctorModel(
    id: 'doc_11',
    name: 'Dr. Priya Sharma',
    email: 'priya.sharma@healthcare.com',
    phone: '+1 234 567 8911',
    specialty: 'Neurologist',
    bio: 'Dr. Priya Sharma specializes in epilepsy, migraine management, and neurodegenerative diseases with a patient-centered approach.',
    education: 'MD - Neurology, Columbia University',
    experienceYears: 9,
    rating: 4.8,
    reviewCount: 2100,
    patientCount: 1400,
    consultationFee: 320,
    isAvailable: true,
    availableDays: ['Mon', 'Tue', 'Thu', 'Fri'],
    availableSlots: ['09:00 AM', '09:30 AM', '10:00 AM', '10:30 AM', '02:00 PM', '02:30 PM', '03:00 PM'],
    hospitalName: 'Neuro Care Institute',
    address: '200 Brain Health Blvd, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_11.jpg',
  ),
  DoctorModel(
    id: 'doc_12',
    name: 'Dr. Alan Foster',
    email: 'alan.foster@healthcare.com',
    phone: '+1 234 567 8912',
    specialty: 'Neurologist',
    bio: 'Dr. Alan Foster is an expert in stroke management, multiple sclerosis, and cognitive neurology with over 14 years of practice.',
    education: 'MD - Neurology, University of Chicago',
    experienceYears: 14,
    rating: 4.7,
    reviewCount: 3200,
    patientCount: 2200,
    consultationFee: 340,
    isAvailable: true,
    availableDays: ['Mon', 'Wed', 'Fri'],
    availableSlots: ['08:30 AM', '09:00 AM', '09:30 AM', '11:00 AM', '11:30 AM', '04:00 PM', '04:30 PM'],
    hospitalName: 'Advanced Neuro Center',
    address: '310 Spine Ave, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_12.jpg',
  ),
  DoctorModel(
    id: 'doc_13',
    name: 'Dr. Nina Patel',
    email: 'nina.patel@healthcare.com',
    phone: '+1 234 567 8913',
    specialty: 'Neurologist',
    bio: 'Dr. Nina Patel focuses on pediatric neurology and adult movement disorders including Parkinson\'s disease.',
    education: 'MD - Neurology, Mayo Clinic School of Medicine',
    experienceYears: 11,
    rating: 4.6,
    reviewCount: 1700,
    patientCount: 1100,
    consultationFee: 310,
    isAvailable: false,
    availableDays: ['Tue', 'Wed', 'Thu'],
    availableSlots: ['10:00 AM', '10:30 AM', '11:00 AM', '03:00 PM', '03:30 PM'],
    hospitalName: 'City General Hospital',
    address: '123 Medical Center Dr, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_13.jpg',
  ),

  // ── Additional Cardiologists ─────────────────────────────────────────────
  DoctorModel(
    id: 'doc_14',
    name: 'Dr. Marcus Brown',
    email: 'marcus.brown@healthcare.com',
    phone: '+1 234 567 8914',
    specialty: 'Cardiologist',
    bio: 'Dr. Marcus Brown specializes in preventive cardiology, arrhythmia treatment, and cardiac imaging.',
    education: 'MD - Cardiology, Mayo Clinic',
    experienceYears: 10,
    rating: 4.7,
    reviewCount: 2600,
    patientCount: 1900,
    consultationFee: 360,
    isAvailable: true,
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu'],
    availableSlots: ['08:00 AM', '08:30 AM', '09:00 AM', '01:00 PM', '01:30 PM', '02:00 PM'],
    hospitalName: 'Heart Care Center',
    address: '456 Cardiac Ave, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_14.jpg',
  ),
  DoctorModel(
    id: 'doc_15',
    name: 'Dr. Rachel Kim',
    email: 'rachel.kim@healthcare.com',
    phone: '+1 234 567 8915',
    specialty: 'Cardiologist',
    bio: 'Dr. Rachel Kim is a specialist in women\'s heart health and advanced echocardiography.',
    education: 'MD - Cardiology, Stanford University',
    experienceYears: 8,
    rating: 4.9,
    reviewCount: 2900,
    patientCount: 2000,
    consultationFee: 370,
    isAvailable: true,
    availableDays: ['Mon', 'Wed', 'Thu', 'Fri'],
    availableSlots: ['09:30 AM', '10:00 AM', '10:30 AM', '11:00 AM', '03:00 PM', '03:30 PM'],
    hospitalName: 'CardioVascular Institute',
    address: '500 Heart Lane, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_15.jpg',
  ),
  DoctorModel(
    id: 'doc_16',
    name: 'Dr. Omar Hassan',
    email: 'omar.hassan@healthcare.com',
    phone: '+1 234 567 8916',
    specialty: 'Cardiologist',
    bio: 'Dr. Omar Hassan is an interventional cardiologist with extensive experience in stent placement and coronary angioplasty.',
    education: 'MD - Interventional Cardiology, University of Michigan',
    experienceYears: 16,
    rating: 4.8,
    reviewCount: 3800,
    patientCount: 2700,
    consultationFee: 400,
    isAvailable: false,
    availableDays: ['Tue', 'Thu', 'Fri'],
    availableSlots: ['10:00 AM', '10:30 AM', '02:00 PM', '02:30 PM', '03:00 PM'],
    hospitalName: 'Heart Care Center',
    address: '456 Cardiac Ave, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_16.jpg',
  ),

  // ── Additional Dermatologists ────────────────────────────────────────────
  DoctorModel(
    id: 'doc_17',
    name: 'Dr. Sophia Turner',
    email: 'sophia.turner@healthcare.com',
    phone: '+1 234 567 8917',
    specialty: 'Dermatologist',
    bio: 'Dr. Sophia Turner is a cosmetic dermatologist specializing in anti-aging treatments, laser therapy, and skin rejuvenation.',
    education: 'MD - Dermatology, UCLA',
    experienceYears: 7,
    rating: 4.8,
    reviewCount: 2200,
    patientCount: 1700,
    consultationFee: 270,
    isAvailable: true,
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    availableSlots: ['09:00 AM', '09:30 AM', '10:00 AM', '10:30 AM', '02:00 PM', '02:30 PM'],
    hospitalName: 'Glow Dermatology Clinic',
    address: '112 Skin Care Rd, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_17.jpg',
  ),
  DoctorModel(
    id: 'doc_18',
    name: 'Dr. Ethan Clark',
    email: 'ethan.clark@healthcare.com',
    phone: '+1 234 567 8918',
    specialty: 'Dermatologist',
    bio: 'Dr. Ethan Clark focuses on pediatric dermatology, eczema, psoriasis, and autoimmune skin diseases.',
    education: 'MD - Dermatology, University of Pennsylvania',
    experienceYears: 12,
    rating: 4.6,
    reviewCount: 1600,
    patientCount: 1200,
    consultationFee: 260,
    isAvailable: true,
    availableDays: ['Mon', 'Wed', 'Fri'],
    availableSlots: ['08:00 AM', '08:30 AM', '09:00 AM', '11:00 AM', '11:30 AM', '04:00 PM'],
    hospitalName: 'Skin Care Clinic',
    address: '789 Derma St, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_18.jpg',
  ),
  DoctorModel(
    id: 'doc_19',
    name: 'Dr. Isabella Moore',
    email: 'isabella.moore@healthcare.com',
    phone: '+1 234 567 8919',
    specialty: 'Dermatologist',
    bio: 'Dr. Isabella Moore is a surgical dermatologist specializing in Mohs surgery for skin cancer and complex wound repairs.',
    education: 'MD - Dermatology & Surgery, Harvard Medical School',
    experienceYears: 15,
    rating: 4.9,
    reviewCount: 2800,
    patientCount: 2100,
    consultationFee: 300,
    isAvailable: false,
    availableDays: ['Tue', 'Thu'],
    availableSlots: ['10:00 AM', '10:30 AM', '11:00 AM', '03:00 PM', '03:30 PM'],
    hospitalName: 'Advanced Skin Institute',
    address: '450 Derma Blvd, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_19.jpg',
  ),

  // ── Additional Pediatricians ─────────────────────────────────────────────
  DoctorModel(
    id: 'doc_20',
    name: 'Dr. Carlos Rivera',
    email: 'carlos.rivera@healthcare.com',
    phone: '+1 234 567 8920',
    specialty: 'Pediatrician',
    bio: 'Dr. Carlos Rivera specializes in adolescent medicine, childhood obesity, and developmental disorders.',
    education: 'MD - Pediatrics, Columbia University',
    experienceYears: 8,
    rating: 4.7,
    reviewCount: 3100,
    patientCount: 2400,
    consultationFee: 190,
    isAvailable: true,
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    availableSlots: ['08:30 AM', '09:00 AM', '09:30 AM', '10:00 AM', '01:00 PM', '01:30 PM', '02:00 PM'],
    hospitalName: 'Children\'s Medical Center',
    address: '321 Kids Ave, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_20.jpg',
  ),
  DoctorModel(
    id: 'doc_21',
    name: 'Dr. Hannah Scott',
    email: 'hannah.scott@healthcare.com',
    phone: '+1 234 567 8921',
    specialty: 'Pediatrician',
    bio: 'Dr. Hannah Scott is a neonatologist with extensive experience in newborn intensive care and premature infant care.',
    education: 'MD - Neonatology, Johns Hopkins University',
    experienceYears: 13,
    rating: 4.9,
    reviewCount: 3700,
    patientCount: 2800,
    consultationFee: 220,
    isAvailable: true,
    availableDays: ['Mon', 'Tue', 'Thu', 'Fri', 'Sat'],
    availableSlots: ['08:00 AM', '08:30 AM', '09:00 AM', '10:00 AM', '10:30 AM', '03:00 PM', '03:30 PM'],
    hospitalName: 'Children\'s Medical Center',
    address: '321 Kids Ave, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_21.jpg',
  ),
  DoctorModel(
    id: 'doc_22',
    name: 'Dr. Liam Walker',
    email: 'liam.walker@healthcare.com',
    phone: '+1 234 567 8922',
    specialty: 'Pediatrician',
    bio: 'Dr. Liam Walker focuses on pediatric allergy, immunology, and infectious diseases in children.',
    education: 'MD - Pediatrics, Yale School of Medicine',
    experienceYears: 6,
    rating: 4.5,
    reviewCount: 1800,
    patientCount: 1300,
    consultationFee: 185,
    isAvailable: true,
    availableDays: ['Tue', 'Wed', 'Thu', 'Fri'],
    availableSlots: ['09:30 AM', '10:00 AM', '10:30 AM', '11:00 AM', '02:30 PM', '03:00 PM'],
    hospitalName: 'Bright Kids Clinic',
    address: '88 Pediatric Way, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_22.jpg',
  ),

  // ── Additional Orthopedic Surgeons ───────────────────────────────────────
  DoctorModel(
    id: 'doc_23',
    name: 'Dr. Natalie Brooks',
    email: 'natalie.brooks@healthcare.com',
    phone: '+1 234 567 8923',
    specialty: 'Orthopedic',
    bio: 'Dr. Natalie Brooks specializes in knee and hip replacement surgeries, sports medicine, and minimally invasive procedures.',
    education: 'MD - Orthopedic Surgery, University of Pittsburgh',
    experienceYears: 11,
    rating: 4.7,
    reviewCount: 2000,
    patientCount: 1600,
    consultationFee: 380,
    isAvailable: true,
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu'],
    availableSlots: ['08:00 AM', '08:30 AM', '09:00 AM', '01:00 PM', '01:30 PM', '02:00 PM'],
    hospitalName: 'Bone & Joint Center',
    address: '654 Ortho Lane, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_23.jpg',
  ),
  DoctorModel(
    id: 'doc_24',
    name: 'Dr. Kevin Nguyen',
    email: 'kevin.nguyen@healthcare.com',
    phone: '+1 234 567 8924',
    specialty: 'Orthopedic',
    bio: 'Dr. Kevin Nguyen is a spine specialist with expertise in scoliosis correction, disc herniation, and spinal fusion.',
    education: 'MD - Spine Surgery, Northwestern University',
    experienceYears: 18,
    rating: 4.8,
    reviewCount: 2700,
    patientCount: 2000,
    consultationFee: 420,
    isAvailable: true,
    availableDays: ['Mon', 'Wed', 'Fri'],
    availableSlots: ['09:00 AM', '09:30 AM', '10:00 AM', '03:00 PM', '03:30 PM', '04:00 PM'],
    hospitalName: 'Spine & Orthopedic Hospital',
    address: '770 Spine Blvd, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_24.jpg',
  ),
  DoctorModel(
    id: 'doc_25',
    name: 'Dr. Zoe Campbell',
    email: 'zoe.campbell@healthcare.com',
    phone: '+1 234 567 8925',
    specialty: 'Orthopedic',
    bio: 'Dr. Zoe Campbell specializes in hand and upper extremity surgery, carpal tunnel syndrome, and tendon repairs.',
    education: 'MD - Orthopedic Surgery, Emory University',
    experienceYears: 9,
    rating: 4.6,
    reviewCount: 1500,
    patientCount: 1100,
    consultationFee: 360,
    isAvailable: false,
    availableDays: ['Tue', 'Thu', 'Fri'],
    availableSlots: ['10:00 AM', '10:30 AM', '11:00 AM', '02:00 PM', '02:30 PM'],
    hospitalName: 'Bone & Joint Center',
    address: '654 Ortho Lane, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_25.jpg',
  ),

  // ── Additional Gynecologists ─────────────────────────────────────────────
  DoctorModel(
    id: 'doc_26',
    name: 'Dr. Amara Osei',
    email: 'amara.osei@healthcare.com',
    phone: '+1 234 567 8926',
    specialty: 'Gynecologist',
    bio: 'Dr. Amara Osei specializes in high-risk pregnancy, maternal-fetal medicine, and minimally invasive gynecological surgery.',
    education: 'MD - OB/GYN, Emory University School of Medicine',
    experienceYears: 13,
    rating: 4.9,
    reviewCount: 3400,
    patientCount: 2600,
    consultationFee: 300,
    isAvailable: true,
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    availableSlots: ['08:30 AM', '09:00 AM', '09:30 AM', '10:00 AM', '02:00 PM', '02:30 PM', '03:00 PM'],
    hospitalName: 'Women\'s Health Center',
    address: '987 Women St, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_26.jpg',
  ),
  DoctorModel(
    id: 'doc_27',
    name: 'Dr. Fatima Malik',
    email: 'fatima.malik@healthcare.com',
    phone: '+1 234 567 8927',
    specialty: 'Gynecologist',
    bio: 'Dr. Fatima Malik focuses on reproductive endocrinology, fertility treatments, and polycystic ovary syndrome management.',
    education: 'MD - Reproductive Medicine, Cornell University',
    experienceYears: 10,
    rating: 4.8,
    reviewCount: 2900,
    patientCount: 2200,
    consultationFee: 290,
    isAvailable: true,
    availableDays: ['Mon', 'Wed', 'Thu', 'Fri'],
    availableSlots: ['09:00 AM', '09:30 AM', '10:30 AM', '11:00 AM', '01:00 PM', '01:30 PM'],
    hospitalName: 'Fertility & Women\'s Clinic',
    address: '220 Womens Way, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_27.jpg',
  ),
  DoctorModel(
    id: 'doc_28',
    name: 'Dr. Clara Nielsen',
    email: 'clara.nielsen@healthcare.com',
    phone: '+1 234 567 8928',
    specialty: 'Gynecologist',
    bio: 'Dr. Clara Nielsen is an expert in adolescent gynecology, menopause management, and urogynecological procedures.',
    education: 'MD - OB/GYN, University of Washington',
    experienceYears: 7,
    rating: 4.6,
    reviewCount: 1900,
    patientCount: 1400,
    consultationFee: 270,
    isAvailable: true,
    availableDays: ['Tue', 'Wed', 'Thu'],
    availableSlots: ['08:00 AM', '08:30 AM', '09:00 AM', '10:00 AM', '03:30 PM', '04:00 PM'],
    hospitalName: 'Women\'s Health Center',
    address: '987 Women St, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_28.jpg',
  ),

  // ── Additional Psychiatrists ─────────────────────────────────────────────
  DoctorModel(
    id: 'doc_29',
    name: 'Dr. Aaron Flynn',
    email: 'aaron.flynn@healthcare.com',
    phone: '+1 234 567 8929',
    specialty: 'Psychiatrist',
    bio: 'Dr. Aaron Flynn specializes in child and adolescent psychiatry, ADHD, and behavioral disorders.',
    education: 'MD - Child Psychiatry, Yale University',
    experienceYears: 8,
    rating: 4.7,
    reviewCount: 1700,
    patientCount: 1000,
    consultationFee: 330,
    isAvailable: true,
    availableDays: ['Mon', 'Tue', 'Thu', 'Fri'],
    availableSlots: ['09:00 AM', '09:30 AM', '10:00 AM', '10:30 AM', '02:00 PM', '02:30 PM'],
    hospitalName: 'Mind Wellness Center',
    address: '147 Mental Health Dr, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_29.jpg',
  ),
  DoctorModel(
    id: 'doc_30',
    name: 'Dr. Mei Zhang',
    email: 'mei.zhang@healthcare.com',
    phone: '+1 234 567 8930',
    specialty: 'Psychiatrist',
    bio: 'Dr. Mei Zhang is a geriatric psychiatrist specializing in dementia-related behavioral symptoms and late-life depression.',
    education: 'MD - Geriatric Psychiatry, UCSF',
    experienceYears: 12,
    rating: 4.6,
    reviewCount: 1400,
    patientCount: 850,
    consultationFee: 340,
    isAvailable: true,
    availableDays: ['Mon', 'Wed', 'Fri'],
    availableSlots: ['10:00 AM', '10:30 AM', '11:00 AM', '03:00 PM', '03:30 PM', '04:00 PM'],
    hospitalName: 'Harmony Psychiatric Clinic',
    address: '300 Calm Street, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_30.jpg',
  ),
  DoctorModel(
    id: 'doc_31',
    name: 'Dr. Sonia Kapoor',
    email: 'sonia.kapoor@healthcare.com',
    phone: '+1 234 567 8931',
    specialty: 'Psychiatrist',
    bio: 'Dr. Sonia Kapoor provides evidence-based therapy for OCD, eating disorders, and trauma-related conditions.',
    education: 'MD - Psychiatry, Boston University',
    experienceYears: 6,
    rating: 4.5,
    reviewCount: 1200,
    patientCount: 720,
    consultationFee: 310,
    isAvailable: false,
    availableDays: ['Tue', 'Thu'],
    availableSlots: ['11:00 AM', '11:30 AM', '01:00 PM', '01:30 PM'],
    hospitalName: 'Mind Wellness Center',
    address: '147 Mental Health Dr, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_31.jpg',
  ),

  // ── Additional Ophthalmologists ──────────────────────────────────────────
  DoctorModel(
    id: 'doc_32',
    name: 'Dr. Lucas Fernandez',
    email: 'lucas.fernandez@healthcare.com',
    phone: '+1 234 567 8932',
    specialty: 'Ophthalmologist',
    bio: 'Dr. Lucas Fernandez is a retina specialist with expertise in diabetic retinopathy, macular degeneration, and vitreoretinal surgery.',
    education: 'MD - Ophthalmology, Duke University',
    experienceYears: 14,
    rating: 4.8,
    reviewCount: 2400,
    patientCount: 1800,
    consultationFee: 295,
    isAvailable: true,
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu'],
    availableSlots: ['08:00 AM', '08:30 AM', '09:00 AM', '09:30 AM', '01:30 PM', '02:00 PM'],
    hospitalName: 'Vision Care Institute',
    address: '258 Eye Lane, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_32.jpg',
  ),
  DoctorModel(
    id: 'doc_33',
    name: 'Dr. Grace Park',
    email: 'grace.park@healthcare.com',
    phone: '+1 234 567 8933',
    specialty: 'Ophthalmologist',
    bio: 'Dr. Grace Park specializes in corneal diseases, dry eye syndrome, and refractive surgery including LASIK and PRK.',
    education: 'MD - Cornea & Refractive Surgery, USC',
    experienceYears: 9,
    rating: 4.7,
    reviewCount: 2000,
    patientCount: 1500,
    consultationFee: 280,
    isAvailable: true,
    availableDays: ['Mon', 'Wed', 'Fri'],
    availableSlots: ['09:00 AM', '09:30 AM', '10:00 AM', '10:30 AM', '03:00 PM', '03:30 PM'],
    hospitalName: 'Clear Vision Eye Center',
    address: '400 Optics Ave, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_33.jpg',
  ),
  DoctorModel(
    id: 'doc_34',
    name: 'Dr. Omar Qureshi',
    email: 'omar.qureshi@healthcare.com',
    phone: '+1 234 567 8934',
    specialty: 'Ophthalmologist',
    bio: 'Dr. Omar Qureshi focuses on glaucoma management, pediatric ophthalmology, and neuro-ophthalmology.',
    education: 'MD - Ophthalmology, University of Toronto',
    experienceYears: 11,
    rating: 4.5,
    reviewCount: 1600,
    patientCount: 1200,
    consultationFee: 265,
    isAvailable: true,
    availableDays: ['Tue', 'Thu', 'Fri'],
    availableSlots: ['08:30 AM', '09:00 AM', '11:00 AM', '11:30 AM', '02:30 PM', '03:00 PM'],
    hospitalName: 'Vision Care Institute',
    address: '258 Eye Lane, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_34.jpg',
  ),

  // ── Additional ENT Specialists ───────────────────────────────────────────
  DoctorModel(
    id: 'doc_35',
    name: 'Dr. Ananya Reddy',
    email: 'ananya.reddy@healthcare.com',
    phone: '+1 234 567 8935',
    specialty: 'ENT Specialist',
    bio: 'Dr. Ananya Reddy is an otolaryngologist specializing in chronic sinusitis, nasal polyps, and endoscopic sinus surgery.',
    education: 'MD - Otolaryngology, Vanderbilt University',
    experienceYears: 8,
    rating: 4.7,
    reviewCount: 1900,
    patientCount: 1400,
    consultationFee: 270,
    isAvailable: true,
    availableDays: ['Mon', 'Tue', 'Wed', 'Fri'],
    availableSlots: ['08:00 AM', '08:30 AM', '09:00 AM', '10:00 AM', '02:00 PM', '02:30 PM'],
    hospitalName: 'ENT Medical Center',
    address: '369 ENT Blvd, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_35.jpg',
  ),
  DoctorModel(
    id: 'doc_36',
    name: 'Dr. Ben Okafor',
    email: 'ben.okafor@healthcare.com',
    phone: '+1 234 567 8936',
    specialty: 'ENT Specialist',
    bio: 'Dr. Ben Okafor specializes in head and neck oncology, thyroid disorders, and voice disorders.',
    education: 'MD - Head & Neck Surgery, Georgetown University',
    experienceYears: 16,
    rating: 4.8,
    reviewCount: 2600,
    patientCount: 1900,
    consultationFee: 290,
    isAvailable: true,
    availableDays: ['Mon', 'Wed', 'Thu'],
    availableSlots: ['09:30 AM', '10:00 AM', '10:30 AM', '11:00 AM', '03:30 PM', '04:00 PM'],
    hospitalName: 'Advanced ENT Clinic',
    address: '520 Throat Ave, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_36.jpg',
  ),
  DoctorModel(
    id: 'doc_37',
    name: 'Dr. Leila Hassan',
    email: 'leila.hassan@healthcare.com',
    phone: '+1 234 567 8937',
    specialty: 'ENT Specialist',
    bio: 'Dr. Leila Hassan is an audiologist and ENT specialist focusing on hearing loss, cochlear implants, and balance disorders.',
    education: 'MD - Neurotology, University of California',
    experienceYears: 10,
    rating: 4.6,
    reviewCount: 1800,
    patientCount: 1300,
    consultationFee: 255,
    isAvailable: false,
    availableDays: ['Tue', 'Thu', 'Sat'],
    availableSlots: ['10:00 AM', '10:30 AM', '11:30 AM', '02:00 PM', '02:30 PM'],
    hospitalName: 'ENT Medical Center',
    address: '369 ENT Blvd, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_37.jpg',
  ),

  // ── Additional General Physicians ────────────────────────────────────────
  DoctorModel(
    id: 'doc_38',
    name: 'Dr. Patrick O\'Brien',
    email: 'patrick.obrien@healthcare.com',
    phone: '+1 234 567 8938',
    specialty: 'General Physician',
    bio: 'Dr. Patrick O\'Brien is a family medicine doctor offering comprehensive care for all ages, from routine check-ups to chronic disease management.',
    education: 'MD - Family Medicine, University of Dublin',
    experienceYears: 20,
    rating: 4.7,
    reviewCount: 3600,
    patientCount: 3200,
    consultationFee: 140,
    isAvailable: true,
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    availableSlots: ['08:00 AM', '08:30 AM', '09:00 AM', '09:30 AM', '10:00 AM', '11:00 AM', '02:00 PM', '03:00 PM', '04:00 PM'],
    hospitalName: 'Community Health Clinic',
    address: '60 Main Street, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_38.jpg',
  ),
  DoctorModel(
    id: 'doc_39',
    name: 'Dr. Aisha Mohammed',
    email: 'aisha.mohammed@healthcare.com',
    phone: '+1 234 567 8939',
    specialty: 'General Physician',
    bio: 'Dr. Aisha Mohammed specializes in preventive medicine, diabetes management, and hypertension care.',
    education: 'MD - Internal Medicine, Cairo University',
    experienceYears: 9,
    rating: 4.5,
    reviewCount: 1800,
    patientCount: 1500,
    consultationFee: 155,
    isAvailable: true,
    availableDays: ['Mon', 'Tue', 'Thu', 'Fri', 'Sat'],
    availableSlots: ['09:00 AM', '09:30 AM', '10:00 AM', '10:30 AM', '01:00 PM', '01:30 PM', '04:30 PM', '05:00 PM'],
    hospitalName: 'City General Hospital',
    address: '123 Medical Center Dr, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_39.jpg',
  ),
  DoctorModel(
    id: 'doc_40',
    name: 'Dr. Samuel Adeyemi',
    email: 'samuel.adeyemi@healthcare.com',
    phone: '+1 234 567 8940',
    specialty: 'General Physician',
    bio: 'Dr. Samuel Adeyemi provides holistic primary care with a focus on lifestyle medicine, weight management, and mental wellness.',
    education: 'MD - General Practice, University of Lagos',
    experienceYears: 7,
    rating: 4.3,
    reviewCount: 1100,
    patientCount: 900,
    consultationFee: 145,
    isAvailable: true,
    availableDays: ['Mon', 'Wed', 'Fri', 'Sat'],
    availableSlots: ['08:30 AM', '09:00 AM', '10:00 AM', '11:00 AM', '02:00 PM', '03:00 PM', '04:00 PM'],
    hospitalName: 'Wellness First Clinic',
    address: '75 Health Ave, New York, NY',
    avatarUrl: 'assets/images/avatars/doctor_40.jpg',
  ),
];
